steps:
  - name: gcr.io/cloud-builders/docker
    args:
      ["build", "-t", "eventms/frontend:dev", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "eventms/frontend:dev"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "--filename",
        "gke/",
        "--location",
        "us-central1-c",
        "--cluster",
        "=my-first-cluster-1"
        "${_SERVICE_NAME}",
      ]